// Module: api — consolidated Playwright specs (14 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';
import { UsersApi } from '../../api/users-api/users-api.api';
import { getPath } from '../../api/base.api';

test("001 - TC-001 — Verify GET /users/1 returns 200 with a non-empty JSON body", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-001 — Verify GET /users/1 returns 200 with a non-empty JSON body");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "header \"content-type\" contains \"application/json\"", '| actual =', String(response.headers()["content-type"] || ''));
  expect(String(response.headers()["content-type"] || ''), "header \"content-type\" should contain \"application/json\"").toContain("application/json");
  console.log('   ↳ assert:', "JSON \"id\" is present", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\" should exist").toBeDefined();

  console.log("  ✓ TC-001: all 3 assertions passed");
});

test("002 - TC-002 — Confirm GET /users/1 returns the id field matching the requested id value 1", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-002 — Confirm GET /users/1 returns the id field matching the requested id value 1");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" is of type number", '| actual =', getPath(body, "id"));
  expect(typeof getPath(body, "id"), "\"id\" should be number").toBe("number");
  console.log('   ↳ assert:', "JSON \"id\" equals 1", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\"").toEqual(1);

  console.log("  ✓ TC-002: all 3 assertions passed");
});

test("003 - TC-003 — Confirm GET /users/1 returns id as a number and name as a string", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-003 — Confirm GET /users/1 returns id as a number and name as a string");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" is of type number", '| actual =', getPath(body, "id"));
  expect(typeof getPath(body, "id"), "\"id\" should be number").toBe("number");
  console.log('   ↳ assert:', "JSON \"name\" is of type string", '| actual =', getPath(body, "name"));
  expect(typeof getPath(body, "name"), "\"name\" should be string").toBe("string");
  console.log('   ↳ assert:', "JSON \"username\" is of type string", '| actual =', getPath(body, "username"));
  expect(typeof getPath(body, "username"), "\"username\" should be string").toBe("string");
  console.log('   ↳ assert:', "JSON \"email\" is of type string", '| actual =', getPath(body, "email"));
  expect(typeof getPath(body, "email"), "\"email\" should be string").toBe("string");

  console.log("  ✓ TC-003: all 5 assertions passed");
});

test("004 - TC-004 — Confirm GET /users/1 returns the nested address object with a string city", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-004 — Confirm GET /users/1 returns the nested address object with a string city");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"address\" is of type object", '| actual =', getPath(body, "address"));
  expect(typeof getPath(body, "address"), "\"address\" should be object").toBe("object");
  console.log('   ↳ assert:', "JSON \"address.city\" is of type string", '| actual =', getPath(body, "address.city"));
  expect(typeof getPath(body, "address.city"), "\"address.city\" should be string").toBe("string");
  console.log('   ↳ assert:', "JSON \"company\" is of type object", '| actual =', getPath(body, "company"));
  expect(typeof getPath(body, "company"), "\"company\" should be object").toBe("object");

  console.log("  ✓ TC-004: all 4 assertions passed");
});

test("005 - TC-005 — Verify GET /users/1 responds within 5000ms on the happy path", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-005 — Verify GET /users/1 responds within 5000ms on the happy path");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "response time is under 5000 ms", '| actual =', usersApi.durationMs);
  expect(usersApi.durationMs, 'response time (ms)').toBeLessThan(5000);

  console.log("  ✓ TC-005: all 2 assertions passed");
});

test("006 - TC-006 — Verify content-type on GET /users/1 happy path is application/json", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-006 — Verify content-type on GET /users/1 happy path is application/json");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "header \"content-type\" contains \"application/json\"", '| actual =', String(response.headers()["content-type"] || ''));
  expect(String(response.headers()["content-type"] || ''), "header \"content-type\" should contain \"application/json\"").toContain("application/json");

  console.log("  ✓ TC-006: all 2 assertions passed");
});

test("007 - TC-007 — Return 404 for GET /users/99999999 when the user id does not exist", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-007 — Return 404 for GET /users/99999999 when the user id does not exist");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/99999999");

  const response = await usersApi.return404ForGETUsers99999999WhenTheUserId();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is 404", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(404);

  console.log("  ✓ TC-007: all 1 assertion passed");
});

test("008 - TC-008 — Return a 4xx for GET /users/abc when a non-numeric id is supplied", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-008 — Return a 4xx for GET /users/abc when a non-numeric id is supplied");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/abc");

  const response = await usersApi.returnA4xxForGETUsersAbcWhenANonNumericIdIs();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response is an error (non-2xx)", '| actual =', response.status());
  expect(response.ok(), 'response should be a non-2xx error').toBeFalsy();

  console.log("  ✓ TC-008: all 1 assertion passed");
});

test("009 - TC-009 — Return a 404 for POST /users/1 when using the wrong HTTP method on the read URL", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-009 — Return a 404 for POST /users/1 when using the wrong HTTP method on the read URL");
  console.log('  → request:', "POST https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.returnA404ForPOSTUsers1WhenUsingTheWrongHTTP();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response is an error (non-2xx)", '| actual =', response.status());
  expect(response.ok(), 'response should be a non-2xx error').toBeFalsy();

  console.log("  ✓ TC-009: all 1 assertion passed");
});

test("010 - TC-010 — Return a 4xx for DELETE-mismatched method GET-only URL is respected on PUT /users/1 without body", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-010 — Return a 4xx for DELETE-mismatched method GET-only URL is respected on PUT /users/1 without body");
  console.log('  → request:', "PATCH https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.returnA4xxForDELETEMismatchedMethodGETOnly();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is under 500", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBeLessThan(500);

  console.log("  ✓ TC-010: all 1 assertion passed");
});

test("011 - TC-011 — Confirm GET /users/1 ignores an unknown query parameter and still returns 200", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-011 — Confirm GET /users/1 ignores an unknown query parameter and still returns 200");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1?foo=bar");

  const response = await usersApi.confirmGETUsers1IgnoresAnUnknownQuery();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" is present", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\" should exist").toBeDefined();

  console.log("  ✓ TC-011: all 2 assertions passed");
});

test("012 - TC-012 — Confirm GET /users/1/ with a trailing slash does not return a 500", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-012 — Confirm GET /users/1/ with a trailing slash does not return a 500");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1/");

  const response = await usersApi.confirmGETUsers1WithATrailingSlashDoesNot();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response status is under 500", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBeLessThan(500);

  console.log("  ✓ TC-012: all 1 assertion passed");
});

test("013 - TC-013 — Confirm GET /users/1 returns a clean 4xx and no echo for an injection-shaped id", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-013 — Confirm GET /users/1 returns a clean 4xx and no echo for an injection-shaped id");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1%27%20OR%20%271%27%3D%271");

  const response = await usersApi.confirmGETUsers1ReturnsAClean4xxAndNoEchoFor();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');

  console.log('   ↳ assert:', "response is an error (non-2xx)", '| actual =', response.status());
  expect(response.ok(), 'response should be a non-2xx error').toBeFalsy();

  console.log("  ✓ TC-013: all 1 assertion passed");
});

test("014 - TC-014 — Confirm GET /users/1 is idempotent by returning 200 on a repeated identical request", async ({ request }) => {
  const usersApi = new UsersApi(request);

  console.log("\n▶ TC-014 — Confirm GET /users/1 is idempotent by returning 200 on a repeated identical request");
  console.log('  → request:', "GET https://jsonplaceholder.typicode.com/users/1");

  const response = await usersApi.verifyGETUsers1Returns200WithANonEmptyJSON();
  console.log('  ← response:', response.status(), '·', usersApi.durationMs + 'ms');
  const body = await usersApi.json(response);

  console.log('   ↳ assert:', "response status is 200", '| actual =', response.status());
  expect(response.status(), 'HTTP status code').toBe(200);
  console.log('   ↳ assert:', "JSON \"id\" equals 1", '| actual =', getPath(body, "id"));
  expect(getPath(body, "id"), "property \"id\"").toEqual(1);

  console.log("  ✓ TC-014: all 2 assertions passed");
});
